### ISSUE TITLE
No Modelica-file

### ISSUE THREAD

**Issue by hubertus65** [xrg-simulation/ClaRaDelay#1]
Hi Ole & XRG: interesting, but strange without a single Modelica file. Is that available in the free version of ClaRa? It shoudl at least be documented.

**Comment by RMFlesch** [comment]
Hello Hubertus, 

I added a Modelica library with some examples in the newest version. This delay is used in SMArtIInt (https://github.com/xrg-simulation/SMArtIInt) and the free version of ClaRa.
